name: Mazana
favicon: null
layout_spectrum: 0
typography_spectrum: 0.66159
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#babbb5'
    - '#94958f'
    - '#686963'
    - '#353534'
  brandStrength: 0
  lightness: 0.8125
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
