name: Mazana
favicon: null
layout_spectrum: 0.6042545593809336
typography_spectrum: 0.7615907415747643
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.4792538289912045
  lightness: 0.051807524636387825
  saturation: 0.15057063126005232
  rhythmicContrast: 0.5835019145160913
purpose: []
